### ISSUE TITLE
wsgi app raise Http500 on /

### ISSUE THREAD

**Issue by Natim** [collective/collective.eggproxy#2]
[ERROR] Error handling request
Traceback (most recent call last):
  File "~/git/collective.eggproxy/apps/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 99, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "~/git/collective.eggproxy/collective/eggproxy/wsgi.py", line 48, in **init**
    if not os.path.isdir(eggs_dir):
  File "~/git/collective.eggproxy/apps/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, instancemethod found

**Comment by Natim** [comment]
My fix :

```
--- a/collective/eggproxy/wsgi.py   Thu Jul 28 03:52:55 2011 +0000
+++ b/collective/eggproxy/wsgi.py   Thu May 03 12:31:01 2012 +0200
@@ -122,6 +122,7 @@
     index_url = local_conf.get('index', None)
     return EggProxyApp(index_url, eggs_dir)

+application = EggProxyApp()

 class Installer(BaseInstaller):
     use_cheetah = False
```

Then I start it like that :

```
gunicorn collective.eggproxy.wsgi:application
```
